/*==============================================================================

Southclaw's Interactivity Framework (SIF) (Formerly: Adventure API)


	SIF/Overview
	{
		SIF is a collection of high-level include scripts to make the
		development of interactive features easy for the developer while
		maintaining quality front-end gameplay for players.
	}


==============================================================================*/

// Dependencies

#include <streamer>
#include <YSI\y_hooks>
#include <YSI\y_timers>
#include <YSI\y_iterate>


// SIF

#include "SIF/Core.pwn"
#include "SIF/Button.pwn"
#include "SIF/Door.pwn"
#include "SIF/Item.pwn"
#include "SIF/Inventory.pwn"
#include "SIF/Container.pwn"
