/*==============================================================================

# Southclaw's Interactivity Framework (SIF)

## Overview

SIF is a collection of high-level include scripts to make the
development of interactive features easy for the developer while
maintaining quality front-end gameplay for players.

## License

- GPLv3

==============================================================================*/


#include "debug.inc"
#include "core.inc"
#include "button.inc"
#include "door.inc"
#include "item.inc"
#include "inventory.inc"
#include "container.inc"


// Tests

#if defined RUN_TESTS

#include "tests/button.pwn"

#endif
