/*==============================================================================

# Southclaw's Interactivity Framework (SIF)

## Overview

SIF is a collection of high-level include scripts to make the
development of interactive features easy for the developer while
maintaining quality front-end gameplay for players.

## License

- GPLv3

==============================================================================*/

#include "action-text"
#include "SIF/debug"
#include "SIF/core"
#include "SIF/button"
#include "SIF/door"
#include "SIF/item"
#include "SIF/inventory"
#include "SIF/container"


// Tests

#if defined RUN_TESTS

#include "tests/button.pwn"

#endif
